---
- name: Install Ruby && Bundler
  hosts: all
  become: true
  tasks:
    - name: Install ruby, git
      apt:
        name:
          - ruby-full
          - ruby-bundler
          - build-essential
          - git
        update_cache: true
        state: present
