---
- name: Configure App
  hosts: app
  become: true
  vars:
    # передается ip внутренней сети типа 10.130.0.24
    db_host: "{{ hostvars['reddit-db'].int_ip }}"
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: enable puma
      systemd:
        name: puma
        enabled: true

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
